# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:7.1"

# Configuration of the build of the application.
build:
    flavor: composer

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysqldb:mysql"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "public"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"
            # The number of seconds whitelisted (static) content should be cached.
            expires: 600
            scripts: true
            allow: true

# The size of the persistent disk of the application (in MB).
disk: 2048
# The mounts that will be performed when the package is deployed.
mounts:
    "/app/cache": "shared:files/cache"
    "/app/config": "shared:files/config"
    "/app/database": "shared:files/database"
    "/app/extensions": "shared:files/app-extensions
    "/public/extensions": "shared:files/pub-extensions"
    "/public/files": "shared:files/files"
    "/public/themes": "shared:files/themes"
    "/public/thumbs": "shared:files/thumbs"

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
      mkdir -p app/cache
      mkdir -p app/database
      mkdir -p app/extensions
    deploy: |
      php platform_config.php
